"""
Django settings for myproject project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os  
from pathlib import Path  

BASE_DIR = Path(__file__).resolve().parent.parent  


_env_path = BASE_DIR.parent / '.env'  
if _env_path.exists():  
    with open(_env_path) as _f:  
        for _line in _f:  
            _line = _line.strip()  
            if _line and not _line.startswith('#') and '=' in _line:
                _k, _v = _line.split('=', 1)  
                os.environ.setdefault(_k.strip(), _v.strip())  

SECRET_KEY = os.environ.get(  
    'DJANGO_SECRET_KEY',  
    'django-insecure-6h23=my(e70mbqermul^04!7o6-vq)&avu93kl_u04_8_k-ie-'  
)
DEBUG = os.environ.get('DEBUG', 'True') == 'True'  
ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '').split(',') if os.environ.get('ALLOWED_HOSTS') else []  




INSTALLED_APPS = [  
    'daphne',  
    'channels',  
    'django.contrib.admin',  
    'django.contrib.auth',  
    'django.contrib.contenttypes',  
    'django.contrib.sessions',  
    'django.contrib.messages',  
    'django.contrib.staticfiles',  
    'accounts',  
    'posts',  
    'chat',  
    'rest_framework',  
    'corsheaders',  
    'rest_framework.authtoken',  
]

MIDDLEWARE = [  
    'django.middleware.security.SecurityMiddleware',  
    'corsheaders.middleware.CorsMiddleware',  
    'django.contrib.sessions.middleware.SessionMiddleware',  
    'django.middleware.common.CommonMiddleware',  
    'django.middleware.csrf.CsrfViewMiddleware',  
    'django.contrib.auth.middleware.AuthenticationMiddleware',  
    'django.contrib.messages.middleware.MessageMiddleware',  
    'django.middleware.clickjacking.XFrameOptionsMiddleware',  
]

ROOT_URLCONF = 'myproject.urls'  

TEMPLATES = [  
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',  
        'DIRS': [],  
        'APP_DIRS': True,  
        'OPTIONS': {
            'context_processors': [  
                'django.template.context_processors.request',  
                'django.contrib.auth.context_processors.auth',  
                'django.contrib.messages.context_processors.messages',  
            ],
        },
    },
]

WSGI_APPLICATION = 'myproject.wsgi.application'  





DATABASES = {  
    'default': {  
        'ENGINE': 'django.db.backends.sqlite3',  
        'NAME': BASE_DIR / 'db.sqlite3',  
    }
}





AUTH_PASSWORD_VALIDATORS = [  
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',  
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',  
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',  
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',  
    },
]





LANGUAGE_CODE = 'ru'  

TIME_ZONE = 'UTC'  

USE_I18N = True  

USE_TZ = True  





STATIC_URL = 'static/'  

AUTH_USER_MODEL = 'accounts.User'  

MEDIA_URL = '/media/'  
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')  

BACKEND_BASE_URL = os.environ.get('BACKEND_BASE_URL', 'http://127.0.0.1:8000')  

LOGIN_URL = 'login'  
LOGIN_REDIRECT_URL = 'profile'  
LOGOUT_REDIRECT_URL = 'login'  

ASGI_APPLICATION = 'myproject.asgi.application'  

CHANNEL_LAYERS = {  
    'default': {
        'BACKEND': 'channels.layers.InMemoryChannelLayer',  
    },
}

CORS_ALLOWED_ORIGINS = [  
    'http://localhost:5173',  
]


EMAIL_HOST = os.environ.get('EMAIL_HOST', '')  
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))  
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')  
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')  
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'  
DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@pingram.dev')  

if EMAIL_HOST and EMAIL_HOST_USER:  
    EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'  
else:  
    EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'  

REST_FRAMEWORK = {  
    'DEFAULT_AUTHENTICATION_CLASSES': [  
        'accounts.authentication.BanAwareTokenAuthentication',  
        'rest_framework.authentication.SessionAuthentication',  
    ],
    'DEFAULT_PERMISSION_CLASSES': [  
        'rest_framework.permissions.IsAuthenticatedOrReadOnly',  
    ],
}
