from django.contrib import admin  
from django.urls import path  
from django.conf import settings  
from django.conf.urls.static import static  

from posts.api_views import (  
    PostListCreateAPI,          
    PostDetailAPI,              
    LikeToggleAPI,              
    CommentListCreateAPI,       
    RepostAPI,                  
    CollectionListCreateAPI,    
    CollectionDetailAPI,        
    AddToCollectionAPI,         
    TagFeedAPI,                 
    ModerationQueueAPI,         
    ModerationLockAPI,          
    ModerationActionAPI,        
    TrendingTagsAPI,            
    TagListAPI,                 
    UserPostsAPI,               
    UserRepostsAPI,             
    UserLikedAPI,               
    UserDraftsAPI,              
    CommentDetailAPI,           
    SimilarPostsAPI,            
    PostReportAPI,              
    ModerationReportListAPI,    
    ModerationReportActionAPI,  
    UserReturnedPostsAPI,       
    CommentLikeToggleAPI,       
    CommentReportAPI,           
    CommentReportListAPI,       
    CommentReportActionAPI,     
    QuoteRepostAPI,             
)
from accounts.api_views import (  
    RegisterAPI,                
    LoginAPI,                   
    MeAPI,                      
    UserProfileAPI,             
    FollowToggleAPI,            
    NotificationListAPI,        
    NotificationMarkReadAPI,    
    NotificationUnreadCountAPI, 
    NotificationDeleteAPI,      
    UserSearchAPI,              
    FollowerListAPI,            
    FollowingListAPI,           
    ChangePasswordAPI,          
    DeleteAccountAPI,           
    WsTicketAPI,                
    BlockToggleAPI,             
    BlockedUsersListAPI,        
    FollowRequestListAPI,       
    FollowRequestActionAPI,     
    UserReportAPI,              
    BanUserAPI,                 
    AdminUserListAPI,           
    UserReportListAPI,          
    UserReportActionAPI,        
)
from chat.api_views import InboxAPI, ConversationAPI, SendImageAPI, MessageDeleteAPI  

urlpatterns = [  
    path('admin/', admin.site.urls),  

    path('api/auth/register/', RegisterAPI.as_view()),  
    path('api/auth/login/', LoginAPI.as_view()),  

    path('api/me/', MeAPI.as_view()),  
    path('api/me/password/', ChangePasswordAPI.as_view()),  
    path('api/me/delete/', DeleteAccountAPI.as_view()),  
    path('api/me/blocked/', BlockedUsersListAPI.as_view()),  
    path('api/me/follow-requests/', FollowRequestListAPI.as_view()),  
    path('api/me/follow-requests/<int:pk>/action/', FollowRequestActionAPI.as_view()),  
    path('api/ws-ticket/', WsTicketAPI.as_view()),  
    path('api/admin/users/', AdminUserListAPI.as_view()),  
    path('api/admin/users/<str:username>/ban/', BanUserAPI.as_view()),  
    path('api/admin/user-reports/', UserReportListAPI.as_view()),  
    path('api/admin/user-reports/<int:pk>/action/', UserReportActionAPI.as_view()),  

    path('api/users/search/', UserSearchAPI.as_view()),  
    path('api/users/<str:username>/', UserProfileAPI.as_view()),  
    path('api/users/<str:username>/follow/', FollowToggleAPI.as_view()),  
    path('api/users/<str:username>/block/', BlockToggleAPI.as_view()),  
    path('api/users/<str:username>/report/', UserReportAPI.as_view()),  
    path('api/users/<str:username>/followers/', FollowerListAPI.as_view()),  
    path('api/users/<str:username>/following/', FollowingListAPI.as_view()),  
    path('api/users/<str:username>/posts/', UserPostsAPI.as_view()),  
    path('api/users/<str:username>/reposts/', UserRepostsAPI.as_view()),  
    path('api/users/<str:username>/liked/', UserLikedAPI.as_view()),  
    path('api/users/<str:username>/drafts/', UserDraftsAPI.as_view()),  
    path('api/users/<str:username>/returned/', UserReturnedPostsAPI.as_view()),  

    path('api/posts/', PostListCreateAPI.as_view()),  
    path('api/posts/moderation/', ModerationQueueAPI.as_view()),  
    path('api/posts/<int:pk>/moderate/lock/', ModerationLockAPI.as_view()),  
    path('api/posts/<int:pk>/moderate/action/', ModerationActionAPI.as_view()),  
    path('api/posts/<int:pk>/', PostDetailAPI.as_view()),  
    path('api/posts/<int:pk>/like/', LikeToggleAPI.as_view()),  
    path('api/posts/<int:pk>/comments/', CommentListCreateAPI.as_view()),  
    path('api/posts/<int:pk>/comments/<int:comment_pk>/', CommentDetailAPI.as_view()),  
    path('api/posts/<int:pk>/comments/<int:comment_pk>/like/', CommentLikeToggleAPI.as_view()),  
    path('api/posts/<int:pk>/comments/<int:comment_pk>/report/', CommentReportAPI.as_view()),  
    path('api/posts/<int:pk>/repost/', RepostAPI.as_view()),  
    path('api/posts/<int:pk>/quote/', QuoteRepostAPI.as_view()),  
    path('api/posts/<int:pk>/similar/', SimilarPostsAPI.as_view()),  
    path('api/posts/<int:pk>/report/', PostReportAPI.as_view()),  

    path('api/moderation/reports/', ModerationReportListAPI.as_view()),  
    path('api/moderation/reports/<int:pk>/action/', ModerationReportActionAPI.as_view()),  
    path('api/moderation/comment-reports/', CommentReportListAPI.as_view()),  
    path('api/moderation/comment-reports/<int:pk>/action/', CommentReportActionAPI.as_view()),  

    path('api/collections/', CollectionListCreateAPI.as_view()),  
    path('api/collections/<int:pk>/', CollectionDetailAPI.as_view()),  
    path('api/collections/<int:pk>/add/', AddToCollectionAPI.as_view()),  

    path('api/tags/', TagListAPI.as_view()),  
    path('api/tags/trending/', TrendingTagsAPI.as_view()),  
    path('api/tags/<slug:slug>/', TagFeedAPI.as_view()),  

    path('api/notifications/', NotificationListAPI.as_view()),  
    path('api/notifications/read/', NotificationMarkReadAPI.as_view()),  
    path('api/notifications/count/', NotificationUnreadCountAPI.as_view()),  
    path('api/notifications/delete-all/', NotificationDeleteAPI.as_view()),  
    path('api/notifications/<int:pk>/', NotificationDeleteAPI.as_view()),  

    path('api/chat/', InboxAPI.as_view()),  
    path('api/chat/<str:username>/', ConversationAPI.as_view()),  
    path('api/chat/<str:username>/image/', SendImageAPI.as_view()),  
    path('api/chat/message/<int:pk>/', MessageDeleteAPI.as_view()),  
]

if settings.DEBUG:  
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  
