# Generated by Django 6.0.4 on 2026-06-22 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_post_media'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hex', models.CharField(max_length=7)),
                ('hue', models.SmallIntegerField()),
                ('saturation', models.SmallIntegerField()),
                ('lightness', models.SmallIntegerField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='posts.post')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
